name = "Ty the Tasmanian Tiger"
home = "https://discord.com/channels/731205301247803413/1111533202184613991"
default_url = "https://github.com/xMcacutt/Archipelago-TyTheTasmanianTiger/releases/download/{{version}}/ty_the_tasmanian_tiger.apworld"

[versions]
"1.1.2" = {}
"1.1.4" = {}
"1.1.7" = {}
"1.2.1" = {}
"1.2.3" = {}
"1.3.1" = {}
"1.3.3" = {}
"1.3.6" = {url = "https://github.com/xMcacutt-Archipelago/Archipelago-TyTheTasmanianTiger/releases/download/1.3.6/ty_the_tasmanian_tiger.apworld"}
"1.3.7" = {url = "https://github.com/xMcacutt-Archipelago/Archipelago-TyTheTasmanianTiger/releases/download/1.3.7/ty_the_tasmanian_tiger.apworld"}
